/**
 * Integration catalog, derived from the Notion Integration Matrix.
 * The agent reasons about capabilities (READ_REVENUE), never vendors (Stripe);
 * adapters declare which capabilities they can satisfy.
 */

export const READ_CAPABILITIES = [
  "READ_REVENUE",
  "READ_SUBSCRIPTIONS",
  "READ_ANALYTICS",
  "READ_PRODUCT_EVENTS",
  "READ_SEARCH_QUERIES",
  "READ_AD_INSIGHTS",
  "READ_SOCIAL_ANALYTICS",
  "READ_EMAIL_METRICS",
  "READ_CRM",
  "READ_PRODUCT_RELEASES",
] as const;

export const WRITE_CAPABILITIES = [
  "CREATE_PAID_CAMPAIGN",
  "UPDATE_AD_BUDGET",
  "PAUSE_CAMPAIGN",
  "PUBLISH_LANDING_PAGE",
  "PUBLISH_SOCIAL_POST",
  "SEND_EMAIL",
  "MANAGE_EMAIL_SEQUENCE",
  "UPDATE_CRM",
  "TRACK_CREATOR_DEALS",
] as const;

export type ReadCapability = (typeof READ_CAPABILITIES)[number];
export type WriteCapability = (typeof WRITE_CAPABILITIES)[number];
export type Capability = ReadCapability | WriteCapability;

export type IntegrationDomain = "revenue" | "analytics" | "search" | "ads" | "social" | "email" | "crm" | "product" | "creators";

export interface IntegrationDefinition {
  provider: string;
  name: string;
  domain: IntegrationDomain;
  priority: "P0" | "P1" | "P2";
  stage: string;
  mustHave: boolean;
  authType: "oauth" | "api_key";
  risk: "read_only" | "publish" | "spend" | "sensitive";
  reads: ReadCapability[];
  writes: WriteCapability[];
  /** What the agent can do better once connected. Shown in onboarding. */
  unlocks: string;
  permissions: { label: string; access: "read" | "write" }[];
  apiNotes: string;
}

export const INTEGRATIONS: IntegrationDefinition[] = [
  {
    provider: "stripe",
    name: "Stripe",
    domain: "revenue",
    priority: "P0",
    stage: "S2 Data Brain",
    mustHave: true,
    authType: "api_key",
    risk: "read_only",
    reads: ["READ_REVENUE", "READ_SUBSCRIPTIONS"],
    writes: [],
    unlocks: "Measure experiments by paying customers and MRR instead of clicks.",
    permissions: [
      { label: "Customers, subscriptions and invoices", access: "read" },
      { label: "Payments, refunds and churn events", access: "read" },
    ],
    apiNotes: "Restricted read-only API key; MRR, subscriptions and 30-day collected revenue.",
  },
  {
    provider: "paddle",
    name: "Paddle",
    domain: "revenue",
    priority: "P1",
    stage: "S2 Data Brain",
    mustHave: false,
    authType: "api_key",
    risk: "read_only",
    reads: ["READ_REVENUE", "READ_SUBSCRIPTIONS"],
    writes: [],
    unlocks: "Same revenue measurement for products billed through Paddle.",
    permissions: [{ label: "Subscriptions and transactions", access: "read" }],
    apiNotes: "Read-only API key scoped to the vendor account.",
  },
  {
    provider: "lemon_squeezy",
    name: "Lemon Squeezy",
    domain: "revenue",
    priority: "P1",
    stage: "S2 Data Brain",
    mustHave: false,
    authType: "api_key",
    risk: "read_only",
    reads: ["READ_REVENUE", "READ_SUBSCRIPTIONS"],
    writes: [],
    unlocks: "Same revenue measurement for products billed through Lemon Squeezy.",
    permissions: [{ label: "Orders and subscriptions", access: "read" }],
    apiNotes: "Read-only API key.",
  },
  {
    provider: "google_analytics",
    name: "Google Analytics 4",
    domain: "analytics",
    priority: "P0",
    stage: "S2 Data Brain",
    mustHave: true,
    authType: "oauth",
    risk: "read_only",
    reads: ["READ_ANALYTICS"],
    writes: [],
    unlocks: "See which sources send visitors that sign up, and where the funnel leaks.",
    permissions: [{ label: "Sessions, sources, events and conversions", access: "read" }],
    apiNotes: "Google OAuth; dimensions/metrics normalized into the internal event model.",
  },
  {
    provider: "posthog",
    name: "PostHog",
    domain: "analytics",
    priority: "P1",
    stage: "S2 Data Brain",
    mustHave: false,
    authType: "api_key",
    risk: "read_only",
    reads: ["READ_ANALYTICS", "READ_PRODUCT_EVENTS"],
    writes: [],
    unlocks: "Tie campaigns to activation, not just signups.",
    permissions: [{ label: "Product events, funnels and cohorts", access: "read" }],
    apiNotes: "Project-scoped API key.",
  },
  {
    provider: "plausible",
    name: "Plausible",
    domain: "analytics",
    priority: "P1",
    stage: "S2 Data Brain",
    mustHave: false,
    authType: "api_key",
    risk: "read_only",
    reads: ["READ_ANALYTICS"],
    writes: [],
    unlocks: "Privacy-friendly traffic and goal conversions by source.",
    permissions: [{ label: "Traffic, sources and goal conversions", access: "read" }],
    apiNotes: "Stats API key per site.",
  },
  {
    provider: "search_console",
    name: "Google Search Console",
    domain: "search",
    priority: "P1",
    stage: "S2 Data Brain",
    mustHave: true,
    authType: "oauth",
    risk: "read_only",
    reads: ["READ_SEARCH_QUERIES"],
    writes: [],
    unlocks: "Find the queries you almost rank for and turn them into pages.",
    permissions: [{ label: "Queries, pages, clicks, impressions and position", access: "read" }],
    apiNotes: "Google OAuth; daily snapshots by page and query.",
  },
  {
    provider: "google_ads",
    name: "Google Ads",
    domain: "ads",
    priority: "P0",
    stage: "S4 Paid",
    mustHave: true,
    authType: "oauth",
    risk: "spend",
    reads: ["READ_AD_INSIGHTS"],
    writes: ["CREATE_PAID_CAMPAIGN", "UPDATE_AD_BUDGET", "PAUSE_CAMPAIGN"],
    unlocks: "Launch high-intent search tests and scale or pause them within your budget rules.",
    permissions: [
      { label: "Campaign, keyword and conversion reports", access: "read" },
      { label: "Create campaigns and change budgets (always within guardrails)", access: "write" },
    ],
    apiNotes: "OAuth plus developer token; spend guardrails enforced outside the agent.",
  },
  {
    provider: "meta_ads",
    name: "Meta Ads",
    domain: "ads",
    priority: "P0",
    stage: "S4 Paid",
    mustHave: true,
    authType: "oauth",
    risk: "spend",
    reads: ["READ_AD_INSIGHTS"],
    writes: ["CREATE_PAID_CAMPAIGN", "UPDATE_AD_BUDGET", "PAUSE_CAMPAIGN"],
    unlocks: "Run creative and audience tests, pause losers automatically.",
    permissions: [
      { label: "Ad account insights", access: "read" },
      { label: "Create campaigns, ad sets and ads; change budgets", access: "write" },
    ],
    apiNotes: "OAuth plus app review; start in Copilot mode.",
  },
  {
    provider: "linkedin_ads",
    name: "LinkedIn Marketing",
    domain: "ads",
    priority: "P2",
    stage: "S4 Paid",
    mustHave: false,
    authType: "oauth",
    risk: "spend",
    reads: ["READ_AD_INSIGHTS"],
    writes: ["CREATE_PAID_CAMPAIGN", "UPDATE_AD_BUDGET", "PAUSE_CAMPAIGN"],
    unlocks: "B2B campaigns when channel fit is strong.",
    permissions: [{ label: "Campaigns, creatives and analytics", access: "write" }],
    apiNotes: "Marketing API permissions can be restrictive; treated as capability-based.",
  },
  {
    provider: "tiktok_ads",
    name: "TikTok for Business",
    domain: "ads",
    priority: "P2",
    stage: "S4 Paid",
    mustHave: false,
    authType: "oauth",
    risk: "spend",
    reads: ["READ_AD_INSIGHTS"],
    writes: ["CREATE_PAID_CAMPAIGN", "PAUSE_CAMPAIGN"],
    unlocks: "Creative and campaign workflow where access is approved.",
    permissions: [{ label: "Campaigns, creatives and reporting", access: "write" }],
    apiNotes: "Access varies by account; organic creative engine ships independently.",
  },
  {
    provider: "x",
    name: "X",
    domain: "social",
    priority: "P1",
    stage: "S3 Organic",
    mustHave: false,
    authType: "oauth",
    risk: "publish",
    reads: ["READ_SOCIAL_ANALYTICS"],
    writes: ["PUBLISH_SOCIAL_POST"],
    unlocks: "Publish approved build-in-public posts and learn which hooks work.",
    permissions: [
      { label: "Post engagement analytics", access: "read" },
      { label: "Publish posts you approved", access: "write" },
    ],
    apiNotes: "API tiers change; drafts remain useful without write access.",
  },
  {
    provider: "linkedin_organic",
    name: "LinkedIn",
    domain: "social",
    priority: "P1",
    stage: "S3 Organic",
    mustHave: false,
    authType: "oauth",
    risk: "publish",
    reads: ["READ_SOCIAL_ANALYTICS"],
    writes: ["PUBLISH_SOCIAL_POST"],
    unlocks: "Founder and company posts, published only after approval.",
    permissions: [{ label: "Publish posts you approved, as you", access: "write" }],
    apiNotes: "Organic scopes separate from ads; never assume personal publishing scope.",
  },
  {
    provider: "resend",
    name: "Resend",
    domain: "email",
    priority: "P1",
    stage: "S3 Organic",
    mustHave: false,
    authType: "api_key",
    risk: "publish",
    reads: ["READ_EMAIL_METRICS"],
    writes: ["SEND_EMAIL", "MANAGE_EMAIL_SEQUENCE"],
    unlocks: "Run lifecycle experiments that move activation and trial conversion.",
    permissions: [
      { label: "Delivery, open and click events", access: "read" },
      { label: "Send approved lifecycle emails from your verified domain", access: "write" },
    ],
    apiNotes: "User provides a verified sending domain.",
  },
  {
    provider: "brevo",
    name: "Brevo",
    domain: "email",
    priority: "P1",
    stage: "S3 Organic",
    mustHave: false,
    authType: "api_key",
    risk: "publish",
    reads: ["READ_EMAIL_METRICS"],
    writes: ["SEND_EMAIL", "MANAGE_EMAIL_SEQUENCE"],
    unlocks: "Segments, campaigns and lifecycle sends with consent policies.",
    permissions: [{ label: "Contacts, segments, campaigns and sends", access: "write" }],
    apiNotes: "Consent and deliverability policies required.",
  },
  {
    provider: "hubspot",
    name: "HubSpot",
    domain: "crm",
    priority: "P2",
    stage: "S7 OS",
    mustHave: false,
    authType: "oauth",
    risk: "sensitive",
    reads: ["READ_CRM"],
    writes: ["UPDATE_CRM"],
    unlocks: "Connect marketing to pipeline for sales-assisted plans.",
    permissions: [{ label: "Contacts, companies, deals; updates need explicit policy", access: "write" }],
    apiNotes: "Object-level scopes; mutations need explicit policy.",
  },
  {
    provider: "attio",
    name: "Attio",
    domain: "crm",
    priority: "P2",
    stage: "S7 OS",
    mustHave: false,
    authType: "oauth",
    risk: "sensitive",
    reads: ["READ_CRM"],
    writes: ["UPDATE_CRM"],
    unlocks: "Lead and pipeline context from a modern CRM.",
    permissions: [{ label: "Records and lists", access: "write" }],
    apiNotes: "Adapter after the revenue and ads loop proves value.",
  },
  {
    provider: "github",
    name: "GitHub",
    domain: "product",
    priority: "P2",
    stage: "S3 Organic",
    mustHave: false,
    authType: "oauth",
    risk: "read_only",
    reads: ["READ_PRODUCT_RELEASES"],
    writes: [],
    unlocks: "Turn what you shipped this week into launch and content opportunities.",
    permissions: [{ label: "Releases and merged pull requests", access: "read" }],
    apiNotes: "Read-first.",
  },
  {
    provider: "creator_tracking",
    name: "Creator & affiliate tracking",
    domain: "creators",
    priority: "P1",
    stage: "S5 Creators",
    mustHave: false,
    authType: "api_key",
    risk: "sensitive",
    reads: [],
    writes: ["TRACK_CREATOR_DEALS"],
    unlocks: "Attribute revenue to creator codes and links.",
    permissions: [
      { label: "Affiliates, visitors, leads and conversions", access: "read" },
      { label: "Create affiliates and referral links for creator deals you approve", access: "write" },
    ],
    apiNotes: "Rewardful API: affiliates, referral links and Stripe-attributed conversions.",
  },
];

export const DOMAIN_LABEL: Record<IntegrationDomain, string> = {
  revenue: "Revenue",
  analytics: "Product analytics",
  search: "Search",
  ads: "Advertising",
  social: "Distribution",
  email: "Email",
  crm: "CRM",
  product: "Product",
  creators: "Creators",
};

export function getIntegration(provider: string): IntegrationDefinition | undefined {
  return INTEGRATIONS.find((i) => i.provider === provider);
}

export function providersFor(capability: Capability): IntegrationDefinition[] {
  return INTEGRATIONS.filter((i) => (i.reads as Capability[]).includes(capability) || (i.writes as Capability[]).includes(capability));
}
