import { describe, expect, it } from "vitest";
import { hashPassword, verifyPassword } from "@/server/auth/password";

describe("admin user management logic", () => {
  it("generates valid scrypt hashes for user passwords", async () => {
    const rawPassword = "Kaya-test-secret-123!";
    const hash = await hashPassword(rawPassword);

    expect(hash.startsWith("scrypt$")).toBe(true);
    const isValid = await verifyPassword(rawPassword, hash);
    expect(isValid).toBe(true);

    const isWrong = await verifyPassword("WrongPassword123!", hash);
    expect(isWrong).toBe(false);
  });

  it("handles auto-generated password complexity", () => {
    const isAutoGenerated = true;
    const generated = "Kaya-" + "a1b2c3" + "-" + "d4e5f6";
    expect(generated.length).toBeGreaterThanOrEqual(8);
    expect(generated.startsWith("Kaya-")).toBe(true);
  });
});
